// <auto-generated />
using System;
using Inventory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domin.Inventory.InventoryAgg.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("IsStack")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("unitprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Domin.Inventory.InventoryAgg.Inventory", b =>
                {
                    b.OwnsMany("Domin.Inventory.InventoryAgg.InventoryOperation", "inventoryOperation", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("id"), 1L, 1);

                            b1.Property<long>("InventoryId")
                                .HasColumnType("bigint");

                            b1.Property<long>("OerderId")
                                .HasColumnType("bigint");

                            b1.Property<long>("count")
                                .HasColumnType("bigint");

                            b1.Property<long>("currentcount")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("date")
                                .HasColumnType("datetime2");

                            b1.Property<string>("disciption")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("operation")
                                .HasColumnType("bit");

                            b1.Property<long>("operationId")
                                .HasColumnType("bigint");

                            b1.HasKey("id");

                            b1.HasIndex("InventoryId");

                            b1.ToTable("InventoryOperation", (string)null);

                            b1.WithOwner("Inventory")
                                .HasForeignKey("InventoryId");

                            b1.Navigation("Inventory");
                        });

                    b.Navigation("inventoryOperation");
                });
#pragma warning restore 612, 618
        }
    }
}
